version: '3.4'

services:
  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101200.0
    restart: always
    ports:
      - "8545:8545"
    volumes:
      - /root/op-geth/datadir:/datadir
      - /root/op-geth/jwt.txt:/jwt.txt
      - /root/op-geth/genesis.json:/genesis.json
    command: >
      --datadir /datadir
      --http
      --http.corsdomain="*"
      --http.vhosts="*"
      --http.addr=0.0.0.0
      --http.api=web3,debug,eth,txpool,net,engine
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.origins="*"
      --ws.api=debug,eth,txpool,net,engine
      --syncmode=full
      --gcmode=archive
      --nodiscover
      --maxpeers=0
      --networkid=<ID>
      --authrpc.vhosts="*"
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.jwtsecret=./jwt.txt
      --rollup.disabletxpoolgossip=true

  op-node:
    image: op-node:1
    ports:
      - "8547:8547"
    restart: always
    volumes:
      - /root/optimism/op-node/jwt.txt:/jwt.txt
      - /root/optimism/op-node/rollup.json:/rollup.json
      - /root/optimism/op-node/opnode_p2p_priv.txt:/opnode_p2p_priv.txt
    command: >
      op-node
      --l2=http://op-geth:8551
      --l1=$L1_RPC
      --l1.rpckind=$RPC_KIND
      --l2.jwt-secret=./jwt.txt
      --verifier.l1-confs=3
      --rollup.config=./rollup.json
      --rpc.addr=0.0.0.0
      --rpc.port=8547
      --p2p.disable
      --rpc.enable-admin
      --sequencer.enabled
      --sequencer.l1-confs=3
      --p2p.sequencer.key=$SEQ_KEY
    depends_on:
      - op-geth  # op-node depends on op-geth startup
